<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaysSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement("
            INSERT INTO payss (alpha_2, nom, langue, iso_langue)
                VALUES
                ('AF', 'Afghanistan', 'Dari', 'fa'),
                ('AL', 'Albanie', 'Albanais', 'sq'),
                ('DZ', 'Algérie', 'Arabe', 'ar'),
                ('AS', 'Samoa américaines', 'Anglais', 'en'),
                ('AD', 'Andorre', 'Catalan', 'ca'),
                ('AO', 'Angola', 'Portugais', 'pt'),
                ('AG', 'Antigua-et-Barbuda', 'Anglais', 'en'),
                ('AR', 'Argentine', 'Espagnol', 'es'),
                ('AM', 'Arménie', 'Arménien', 'hy'),
                ('AU', 'Australie', 'Anglais', 'en'),
                ('AT', 'Autriche', 'Allemand', 'de'),
                ('AZ', 'Azerbaïdjan', 'Azerbaïdjanais', 'az'),
                ('BS', 'Bahamas', 'Anglais', 'en'),
                ('BH', 'Bahreïn', 'Arabe', 'ar'),
                ('BD', 'Bangladesh', 'Bengali', 'bn'),
                ('BB', 'Barbade', 'Anglais', 'en'),
                ('BY', 'Biélorussie', 'Biélorusse', 'be'),
                ('BE', 'Belgique', 'Français', 'fr'),
                ('BZ', 'Belize', 'Anglais', 'en'),
                ('BJ', 'Bénin', 'Français', 'fr'),
                ('BM', 'Bermudes', 'Anglais', 'en'),
                ('BT', 'Bhoutan', 'Dzongkha', 'dz'),
                ('BO', 'Bolivie', 'Espagnol', 'es'),
                ('BA', 'Bosnie-Herzégovine', 'Bosnien', 'bs'),
                ('BW', 'Botswana', 'Anglais', 'en'),
                ('BR', 'Brésil', 'Portugais', 'pt'),
                ('BN', 'Brunei', 'Malais', 'ms'),
                ('BG', 'Bulgarie', 'Bulgare', 'bg'),
                ('BF', 'Burkina Faso', 'Français', 'fr'),
                ('BI', 'Burundi', 'Kirundi', 'rn'),
                ('KH', 'Cambodge', 'Khmer', 'km'),
                ('CM', 'Cameroun', 'Français', 'fr'),
                ('CA', 'Canada', 'Anglais', 'en'),
                ('CV', 'Cap-Vert', 'Portugais', 'pt'),
                ('CF', 'République centrafricaine', 'Français', 'fr'),
                ('TD', 'Tchad', 'Français', 'fr'),
                ('CL', 'Chili', 'Espagnol', 'es'),
                ('CN', 'Chine', 'Mandarin', 'zh'),
                ('CO', 'Colombie', 'Espagnol', 'es'),
                ('KM', 'Comores', 'Comorien', 'ar'),
                ('CG', 'Congo', 'Français', 'fr'),
                ('CD', 'République Démocratique du Congo', 'Français', 'fr'),
                ('CR', 'Costa Rica', 'Espagnol', 'es'),
                ('HR', 'Croatie', 'Croate', 'hr'),
                ('CU', 'Cuba', 'Espagnol', 'es'),
                ('CY', 'Chypre', 'Grec', 'el'),
                ('CZ', 'République Tchèque', 'Tchèque', 'cs'),
                ('DK', 'Danemark', 'Danois', 'da'),
                ('DJ', 'Djibouti', 'Français', 'fr'),
                ('DM', 'Dominique', 'Anglais', 'en'),
                ('DO', 'République Dominicaine', 'Espagnol', 'es'),
                ('EC', 'Équateur', 'Espagnol', 'es'),
                ('EG', 'Égypte', 'Arabe', 'ar'),
                ('SV', 'Salvador', 'Espagnol', 'es'),
                ('GQ', 'Guinée équatoriale', 'Espagnol', 'es'),
                ('ER', 'Érythrée', 'Tigrigna', 'ti'),
                ('EE', 'Estonie', 'Estonien', 'et'),
                ('ET', 'Éthiopie', 'Amharique', 'am'),
                ('FJ', 'Fidji', 'Anglais', 'en'),
                ('FI', 'Finlande', 'Finnois', 'fi'),
                ('FR', 'France', 'Français', 'fr'),
                ('GA', 'Gabon', 'Français', 'fr'),
                ('GM', 'Gambie', 'Anglais', 'en'),
                ('GE', 'Géorgie', 'Géorgien', 'ka'),
                ('DE', 'Allemagne', 'Allemand', 'de'),
                ('GH', 'Ghana', 'Anglais', 'en'),
                ('GR', 'Grèce', 'Grec', 'el'),
                ('GD', 'Grenade', 'Anglais', 'en'),
                ('GT', 'Guatemala', 'Espagnol', 'es'),
                ('GN', 'Guinée', 'Français', 'fr'),
                ('GW', 'Guinée-Bissau', 'Portugais', 'pt'),
                ('GY', 'Guyana', 'Anglais', 'en'),
                ('HT', 'Haïti', 'Créole', 'ht'),
                ('HN', 'Honduras', 'Espagnol', 'es'),
                ('HU', 'Hongrie', 'Hongrois', 'hu'),
                ('IS', 'Islande', 'Islandais', 'is'),
                ('IN', 'Inde', 'Hindi', 'hi'),
                ('ID', 'Indonésie', 'Indonésien', 'id'),
                ('IR', 'Iran', 'Persan', 'fa'),
                ('IQ', 'Irak', 'Arabe', 'ar'),
                ('IE', 'Irlande', 'Anglais', 'en'),
                ('IL', 'Israël', 'Hébreu', 'he'),
                ('IT', 'Italie', 'Italien', 'it'),
                ('JM', 'Jamaïque', 'Anglais', 'en'),
                ('JP', 'Japon', 'Japonais', 'ja'),
                ('JO', 'Jordanie', 'Arabe', 'ar'),
                ('KZ', 'Kazakhstan', 'Kazakh', 'kk'),
                ('KE', 'Kenya', 'Swahili', 'sw'),
                ('KI', 'Kiribati', 'Anglais', 'en'),
                ('KW', 'Koweït', 'Arabe', 'ar'),
                ('KG', 'Kirghizistan', 'Kirghiz', 'ky'),
                ('LA', 'Laos', 'Lao', 'lo'),
                ('LV', 'Lettonie', 'Letton', 'lv'),
                ('LB', 'Liban', 'Arabe', 'ar'),
                ('LS', 'Lesotho', 'Sotho', 'st'),
                ('LR', 'Liberia', 'Anglais', 'en'),
                ('LY', 'Libye', 'Arabe', 'ar'),
                ('LI', 'Liechtenstein', 'Allemand', 'de'),
                ('LT', 'Lituanie', 'Lituanien', 'lt'),
                ('LU', 'Luxembourg', 'Luxembourgeois', 'lb'),
                ('MG', 'Madagascar', 'Malgache', 'mg'),
                ('MW', 'Malawi', 'Anglais', 'en'),
                ('MY', 'Malaisie', 'Malais', 'ms'),
                ('MV', 'Maldives', 'Divehi', 'dv'),
                ('ML', 'Mali', 'Français', 'fr'),
                ('MT', 'Malte', 'Maltais', 'mt'),
                ('MH', 'Îles Marshall', 'Marshallais', 'mh'),
                ('MR', 'Mauritanie', 'Arabe', 'ar'),
                ('MU', 'Maurice', 'Anglais', 'en'),
                ('MX', 'Mexique', 'Espagnol', 'es'),
                ('FM', 'Micronésie', 'Anglais', 'en'),
                ('MD', 'Moldavie', 'Roumain', 'ro'),
                ('MC', 'Monaco', 'Français', 'fr'),
                ('MN', 'Mongolie', 'Mongol', 'mn'),
                ('ME', 'Monténégro', 'Monténégrin', 'sr'),
                ('MA', 'Maroc', 'Arabe', 'ar'),
                ('MZ', 'Mozambique', 'Portugais', 'pt'),
                ('MM', 'Myanmar', 'Birman', 'my'),
                ('NA', 'Namibie', 'Anglais', 'en'),
                ('NR', 'Nauru', 'Nauruan', 'na'),
                ('NP', 'Népal', 'Népalais', 'ne'),
                ('NL', 'Pays-Bas', 'Néerlandais', 'nl'),
                ('NZ', 'Nouvelle-Zélande', 'Anglais', 'en'),
                ('NI', 'Nicaragua', 'Espagnol', 'es'),
                ('NE', 'Niger', 'Français', 'fr'),
                ('NG', 'Nigeria', 'Anglais', 'en'),
                ('NO', 'Norvège', 'Norvégien', 'no'),
                ('OM', 'Oman', 'Arabe', 'ar'),
                ('PK', 'Pakistan', 'Ourdou', 'ur'),
                ('PW', 'Palaos', 'Anglais', 'en'),
                ('PA', 'Panama', 'Espagnol', 'es'),
                ('PG', 'Papouasie-Nouvelle-Guinée', 'Tok Pisin', 'tpi'),
                ('PY', 'Paraguay', 'Espagnol', 'es'),
                ('PE', 'Pérou', 'Espagnol', 'es'),
                ('PH', 'Philippines', 'Tagalog', 'tl'),
                ('PL', 'Pologne', 'Polonais', 'pl'),
                ('PT', 'Portugal', 'Portugais', 'pt'),
                ('QA', 'Qatar', 'Arabe', 'ar'),
                ('RO', 'Roumanie', 'Roumain', 'ro'),
                ('RU', 'Russie', 'Russe', 'ru'),
                ('RW', 'Rwanda', 'Kinyarwanda', 'rw'),
                ('WS', 'Samoa', 'Samoan', 'sm'),
                ('SM', 'Saint-Marin', 'Italien', 'it'),
                ('ST', 'Sao Tomé-et-Principe', 'Portugais', 'pt'),
                ('SA', 'Arabie Saoudite', 'Arabe', 'ar'),
                ('SN', 'Sénégal', 'Français', 'fr'),
                ('RS', 'Serbie', 'Serbe', 'sr'),
                ('SC', 'Seychelles', 'Français', 'fr'),
                ('SL', 'Sierra Leone', 'Anglais', 'en'),
                ('SG', 'Singapour', 'Anglais', 'en'),
                ('SK', 'Slovaquie', 'Slovaque', 'sk'),
                ('SI', 'Slovénie', 'Slovène', 'sl'),
                ('SB', 'Îles Salomon', 'Anglais', 'en'),
                ('SO', 'Somalie', 'Somali', 'so'),
                ('ZA', 'Afrique du Sud', 'Anglais', 'en'),
                ('ES', 'Espagne', 'Espagnol', 'es'),
                ('LK', 'Sri Lanka', 'Cinghalais', 'si'),
                ('SD', 'Soudan', 'Arabe', 'ar'),
                ('SR', 'Suriname', 'Néerlandais', 'nl'),
                ('SZ', 'Eswatini', 'Swati', 'ss'),
                ('SE', 'Suède', 'Suédois', 'sv'),
                ('CH', 'Suisse', 'Allemand', 'de'),
                ('SY', 'Syrie', 'Arabe', 'ar'),
                ('TW', 'Taïwan', 'Mandarin', 'zh'),
                ('TJ', 'Tadjikistan', 'Tadjik', 'tg'),
                ('TZ', 'Tanzanie', 'Swahili', 'sw'),
                ('TH', 'Thaïlande', 'Thaï', 'th'),
                ('TG', 'Togo', 'Français', 'fr'),
                ('TO', 'Tonga', 'Tongien', 'to'),
                ('TT', 'Trinité-et-Tobago', 'Anglais', 'en'),
                ('TN', 'Tunisie', 'Arabe', 'ar'),
                ('TR', 'Turquie', 'Turc', 'tr'),
                ('TM', 'Turkménistan', 'Turkmène', 'tk'),
                ('TV', 'Tuvalu', 'Tuvaluan', 'tv'),
                ('UG', 'Ouganda', 'Anglais', 'en'),
                ('UA', 'Ukraine', 'Ukrainien', 'uk'),
                ('AE', 'Émirats arabes unis', 'Arabe', 'ar'),
                ('GB', 'Royaume-Uni', 'Anglais', 'en'),
                ('US', 'États-Unis', 'Anglais', 'en'),
                ('UY', 'Uruguay', 'Espagnol', 'es'),
                ('UZ', 'Ouzbékistan', 'Ouzbek', 'uz'),
                ('VU', 'Vanuatu', 'Bichelamar', 'bi'),
                ('VA', 'Vatican', 'Italien', 'it'),
                ('VE', 'Venezuela', 'Espagnol', 'es'),
                ('VN', 'Vietnam', 'Vietnamien', 'vi'),
                ('EH', 'Sahara Occidental', 'Arabe', 'ar'),
                ('YE', 'Yémen', 'Arabe', 'ar'),
                ('ZM', 'Zambie', 'Anglais', 'en'),
                ('ZW', 'Zimbabwe', 'Anglais', 'en');

        ");
    }
}
