<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaysSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement("
            INSERT INTO payss (nom, alpha_2) VALUES
                ('Hong-Kong', 'HK'),
                ('Macau', 'MO'),
                ('Afghanistan', 'AF'),
                ('Afrique du Sud', 'ZA'),
                ('Albanie', 'AL'),
                ('Algérie', 'DZ'),
                ('Allemagne', 'DE'),
                ('Andorre', 'AD'),
                ('Angola', 'AO'),
                ('Antigua-et-Barbuda', 'AG'),
                ('Arabie Saoudite', 'SA'),
                ('Argentine', 'AR'),
                ('Arménie', 'AM'),
                ('Australie', 'AU'),
                ('Autriche', 'AT'),
                ('Azerbaïdjan', 'AZ'),
                ('Bahamas', 'BS'),
                ('Bahreïn', 'BH'),
                ('Bangladesh', 'BD'),
                ('Barbade', 'BB'),
                ('Biélorussie', 'BY'),
                ('Belgique', 'BE'),
                ('Belize', 'BZ'),
                ('Bénin', 'BJ'),
                ('Bhoutan', 'BT'),
                ('Bolivie', 'BO'),
                ('Bosnie-Herzégovine', 'BA'),
                ('Botswana', 'BW'),
                ('Brésil', 'BR'),
                ('Brunei', 'BN'),
                ('Bulgarie', 'BG'),
                ('Burkina Faso', 'BF'),
                ('Burundi', 'BI'),
                ('Cambodge', 'KH'),
                ('Cameroun', 'CM'),
                ('Canada', 'CA'),
                ('Cap-Vert', 'CV'),
                ('Chili', 'CL'),
                ('Chine', 'CN'),
                ('Chypre', 'CY'),
                ('Colombie', 'CO'),
                ('Comores', 'KM'),
                ('Congo (Congo-Brazzaville)', 'CG'),
                ('Congo (République démocratique)', 'CD'),
                ('Costa Rica', 'CR'),
                ('Croatie', 'HR'),
                ('Cuba', 'CU'),
                ('Danemark', 'DK'),
                ('Djibouti', 'DJ'),
                ('Dominique', 'DM'),
                ('Égypte', 'EG'),
                ('Salvador', 'SV'),
                ('Émirats arabes unis', 'AE'),
                ('Équateur', 'EC'),
                ('Érythrée', 'ER'),
                ('Espagne', 'ES'),
                ('Estonie', 'EE'),
                ('États-Unis', 'US'),
                ('Éthiopie', 'ET'),
                ('Fidji', 'FJ'),
                ('Finlande', 'FI'),
                ('France', 'FR'),
                ('Gabon', 'GA'),
                ('Gambie', 'GM'),
                ('Géorgie', 'GE'),
                ('Ghana', 'GH'),
                ('Grèce', 'GR'),
                ('Grenade', 'GD'),
                ('Guatemala', 'GT'),
                ('Guinée', 'GN'),
                ('Guinée équatoriale', 'GQ'),
                ('Guinée-Bissau', 'GW'),
                ('Haïti', 'HT'),
                ('Honduras', 'HN'),
                ('Hongrie', 'HU'),
                ('Inde', 'IN'),
                ('Indonésie', 'ID'),
                ('Irlande', 'IE'),
                ('Islande', 'IS'),
                ('Israël', 'IL'),
                ('Italie', 'IT'),
                ('Jamaïque', 'JM'),
                ('Japon', 'JP'),
                ('Jordanie', 'JO'),
                ('Kazakhstan', 'KZ'),
                ('Kenya', 'KE'),
                ('Kirghizistan', 'KG'),
                ('Kiribati', 'KI'),
                ('Koweït', 'KW'),
                ('Laos', 'LA'),
                ('Lesotho', 'LS'),
                ('Lettonie', 'LV'),
                ('Liban', 'LB'),
                ('Libye', 'LY'),
                ('Lituanie', 'LT'),
                ('Luxembourg', 'LU'),
                ('Madagascar', 'MG'),
                ('Malaisie', 'MY'),
                ('Malawi', 'MW'),
                ('Maldives', 'MV'),
                ('Mali', 'ML'),
                ('Malte', 'MT'),
                ('Marshall (îles)', 'MH'),
                ('Mauritanie', 'MR'),
                ('Maurice', 'MU'),
                ('Mexique', 'MX'),
                ('Micronésie', 'FM'),
                ('Moldavie', 'MD'),
                ('Monaco', 'MC'),
                ('Mongolie', 'MN'),
                ('Monténégro', 'ME'),
                ('Mozambique', 'MZ'),
                ('Namibie', 'NA'),
                ('Nauru', 'NR'),
                ('Népal', 'NP'),
                ('Nicaragua', 'NI'),
                ('Niger', 'NE'),
                ('Nigeria', 'NG'),
                ('Norvège', 'NO'),
                ('Nouvelle-Zélande', 'NZ'),
                ('Oman', 'OM'),
                ('Pakistan', 'PK'),
                ('Palau', 'PW'),
                ('Panama', 'PA'),
                ('Papouasie-Nouvelle-Guinée', 'PG'),
                ('Paraguay', 'PY'),
                ('Pays-Bas', 'NL'),
                ('Pérou', 'PE'),
                ('Philippines', 'PH'),
                ('Pologne', 'PL'),
                ('Portugal', 'PT'),
                ('Qatar', 'QA'),
                ('Roumanie', 'RO'),
                ('Royaume-Uni', 'GB'),
                ('Russie', 'RU'),
                ('Rwanda', 'RW'),
                ('Saint-Kitts-et-Nevis', 'KN'),
                ('Saint-Vincent-et-les-Grenadines', 'VC'),
                ('Salomon (îles)', 'SB'),
                ('Samoa', 'WS'),
                ('Sao Tomé-et-Principe', 'ST'),
                ('Sénégal', 'SN'),
                ('Serbie', 'RS'),
                ('Seychelles', 'SC'),
                ('Sierra Leone', 'SL'),
                ('Singapour', 'SG'),
                ('Slovaquie', 'SK'),
                ('Slovénie', 'SI'),
                ('Somalie', 'SO'),
                ('Soudan', 'SD'),
                ('Soudan du Sud', 'SS'),
                ('Sri Lanka', 'LK'),
                ('Suède', 'SE'),
                ('Suisse', 'CH'),
                ('Syrie', 'SY'),
                ('Tadjikistan', 'TJ'),
                ('Tanzanie', 'TZ'),
                ('Tchad', 'TD'),
                ('Tchéquie', 'CZ'),
                ('Thaïlande', 'TH'),
                ('Timor oriental', 'TL'),
                ('Togo', 'TG'),
                ('Trinité-et-Tobago', 'TT'),
                ('Tunisie', 'TN'),
                ('Turkménistan', 'TM'),
                ('Turquie', 'TR'),
                ('Tuvalu', 'TV'),
                ('Ukraine', 'UA'),
                ('Uruguay', 'UY'),
                ('Vanuatu', 'VU'),
                ('Vatican', 'VA'),
                ('Venezuela', 'VE'),
                ('Viêt Nam', 'VN'),
                ('Yémen', 'YE'),
                ('Zambie', 'ZM'),
                ('Zimbabwe', 'ZW'),
                ('Inconnu', 'XX');

        ");
    }
}
